export enum ServiceType {
  SUNDAY_SERVICE = 'SUNDAY_SERVICE',
  BIBLE_STUDY = 'BIBLE_STUDY',
  PRAYER_MEETING = 'PRAYER_MEETING',
  YOUTH_SERVICE = 'YOUTH_SERVICE',
  CHILDREN_SERVICE = 'CHILDREN_SERVICE',
  SPECIAL_EVENT = 'SPECIAL_EVENT',
  MIDWEEK_SERVICE = 'MIDWEEK_SERVICE',
  OTHER = 'OTHER',
}
